name: compas_fab
channels:
  - tesseract-robotics
  - robotology
  - conda-forge
  - defaults
dependencies:
  - tesseract-robotics-superpack=0.1
  - pybullet=3.1
  - pip
  - pip:
      - -r file:requirements.txt # see setup.py
